name: pvparena
main: it.angaronigiovanni.pvparena.Plugin
version: 0.0.1
api-version: 1.15
author: Gio_A
description: This plugin will provide a new dimension in the server, which is the PVPArena
commands: 
  minigame:
    usage: /minigame
    description: Sends you to a minigame dimension
  
  disable:
    usage: /disable plugin
    description: disable the PVPArena plugin

